language: php
php:
    - 5.6
    - 7.2
    - 7.3
    - 7.4
addons:
  sonarcloud:
      organization: "webfiori"
      token:
          secure: kWfkcs9po5O6Xl64onZCoPT1dW4X2hqdNFtAE7d1t4p4d8IxAjQTdReiMngIfk+aj8jfCm4ALmTbpGxQps+tNZByHx6AF7Ym+ePxchExSA/e/nieiaRUtBxz+zkhL0btRGU1N8havKk1Sr6kSpS5uDhc533Nf+PHlQpe8QmCB1AcJEbv7A/Augfj+FhtqZLd16reIedBw1UIcJxQv24Pqiug0jsjeokR4z7wKd1IPAMVAes8e/f/F/WgeFD5W5hzteVLKIf9hwhgcO1JvDSQrZ4ym6FKqj5hokzpoB8hUclfj5aWoUQI2DV0YbBpY9MwP4ZQv3olVbbTPCZT1Y770YU9u81zHwo9cywge6jzzZlnGR8ekvIhVMV/0n8MPy7RnEn5FZvM5QsZH4VciYSZYa5QEm8U4qGJbJBhcbBegn3dKzh2hz1rjii9fY0SC5vc1xCWpmtUy7mZJbWyWet0Mlw7UOEEy6rBGmVv3MmTl32MW4+Y8O5pJ6F5Zmkb+y3CmvT+dKAnPrTQt5JiPLnwm15qwtHN/MLxfdweyCoIssRSqwvW3xBvkw2BA97oG2PidpzKML7Xqma6O9BgYw6F1O3u+BSoOcTKzW/1bsS8c9icn5raGAVk8Zzdqg9aIzaua95zpOG0T3N4Yt12y+TK0np3EFEptk+J04KueMuesRs=
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
script:
    - phpunit --verbose --configuration phpunit.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - sonar-scanner
    