language: php
php:
    - 5.6
    - 7.2
    - 7.3
    - 7.4
addons:
  sonarcloud:
      organization: "webfiori"
      token:
          secure: Bxw3ZAVP+m05S3tLhumqEgeIDYXq8KAvQR6MRhKht6jWeZHMhFugf00oa+1A+WBi/+/aGImjEtwDUJCw5S24iZHq217Xa7iCKGYn7kIZjCvTB1Pr4f0+Rx3sRzX/9WsIPZLvfC9F2Kypx3WpB2lXJR7gZkfdOVZnGIMKuVf9g/krM5K1UWY9FtmoUsKhdrcRxPVbYy9J5b6R+Qb7hJdgTmH0UFq1LssZxRrqYAwGwat4U5i2p3iAn0QvhrQ2R06Y/W2dO+OhWAzbROhz+CzP+lM+qDWTCUrZDVSHY0Iz9i6tFDRn5DaLBq/+kwowQbS3P1DGmfkMUgyvxozRjVshOvF890DobUYXi4yHmNX8TYC+YzB3PFlySd/NPyNwXOHRUgtsJW7l/I0n6k6mLoLmGJMvQqfR+B2OxP3jC6QVxtPV9G02mCBYjdv1wVfNwabMEt9U84g6mBHLJoBdb3l/T3eGxNpGkb+IHQIhYkXXYfRAdUr6FOh/lUcXSFjr5H7LnHK0MqMiNBlKD0aOdNWvLLsgR1PLy5yFFQy5pVyjg439UKvoy1iZd/zmXWua/aTzN7D7ugSOFZut44cCmrzWXVJUmRLGUgj5k8P7vko6C5bbb56sJrXn02NKKWTCRUqexzlcjscRSoEkiBXfNrpH7DkDNgFm4/aAA773hFZ8A1o=
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
script:
    - phpunit --verbose --configuration phpunit.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - sonar-scanner
    