<?php

/**
 * This file is licensed under MIT License.
 * 
 * Copyright (c) 2025-present WebFiori Framework
 * 
 * For more information on the license, please visit: 
 * https://github.com/WebFiori/.github/blob/main/LICENSE
 * 
 */
namespace WebFiori\Http\OpenAPI;

use WebFiori\Json\Json;
use WebFiori\Json\JsonI;

/**
 * Represents a Security Scheme Object in OpenAPI specification.
 * 
 * Defines a security scheme that can be used by the operations.
 * 
 * Supported schemes are HTTP authentication, an API key (either as a header, 
 * a cookie parameter or as a query parameter), mutual TLS (use of a client certificate), 
 * OAuth2's common flows (implicit, password, client credentials and authorization code) 
 * as defined in RFC6749, and OpenID Connect Discovery.
 * 
 * This object MAY be extended with Specification Extensions.
 * 
 * @see https://spec.openapis.org/oas/v3.1.0#security-scheme-object
 */
class SecuritySchemeObj implements JsonI {
    /**
     * A hint to the client to identify how the bearer token is formatted.
     * 
     * Bearer tokens are usually generated by an authorization server, 
     * so this information is primarily for documentation purposes.
     * 
     * Applies to http ("bearer") type.
     * 
     * @var string|null
     */
    private ?string $bearerFormat = null;

    /**
     * A description for security scheme.
     * 
     * CommonMark syntax MAY be used for rich text representation.
     * 
     * @var string|null
     */
    private ?string $description = null;

    /**
     * An object containing configuration information for the flow types supported.
     * 
     * REQUIRED for oauth2 type.
     * 
     * @var OAuthFlowsObj|null
     */
    private ?OAuthFlowsObj $flows = null;

    /**
     * The location of the API key.
     * 
     * Valid values are "query", "header", or "cookie".
     * 
     * REQUIRED for apiKey type.
     * 
     * @var string|null
     */
    private ?string $in = null;

    /**
     * The name of the header, query or cookie parameter to be used.
     * 
     * REQUIRED for apiKey type.
     * 
     * @var string|null
     */
    private ?string $name = null;

    /**
     * Well-known URL to discover the OpenID Connect provider metadata.
     * 
     * REQUIRED for openIdConnect type.
     * 
     * @var string|null
     */
    private ?string $openIdConnectUrl = null;

    /**
     * The name of the HTTP Authentication scheme.
     * 
     * The values used SHOULD be registered in the IANA Authentication Scheme registry.
     * 
     * REQUIRED for http type.
     * 
     * @var string|null
     */
    private ?string $scheme = null;
    /**
     * The type of the security scheme.
     * 
     * Valid values are "apiKey", "http", "mutualTLS", "oauth2", "openIdConnect".
     * 
     * REQUIRED.
     * 
     * @var string
     */
    private string $type;

    /**
     * Creates new instance.
     * 
     * @param string $type The type of the security scheme. REQUIRED.
     * Valid values are "apiKey", "http", "mutualTLS", "oauth2", "openIdConnect".
     */
    public function __construct(string $type) {
        $this->setType($type);
    }

    /**
     * Returns the bearer token format.
     * 
     * @return string|null Returns the value, or null if not set.
     */
    public function getBearerFormat(): ?string {
        return $this->bearerFormat;
    }

    /**
     * Returns the description.
     * 
     * @return string|null Returns the value, or null if not set.
     */
    public function getDescription(): ?string {
        return $this->description;
    }

    /**
     * Returns the OAuth flows configuration.
     * 
     * @return OAuthFlowsObj|null Returns the value, or null if not set.
     */
    public function getFlows(): ?OAuthFlowsObj {
        return $this->flows;
    }

    /**
     * Returns the location of the API key.
     * 
     * @return string|null Returns the value, or null if not set.
     */
    public function getIn(): ?string {
        return $this->in;
    }

    /**
     * Returns the parameter name.
     * 
     * @return string|null Returns the value, or null if not set.
     */
    public function getName(): ?string {
        return $this->name;
    }

    /**
     * Returns the OpenID Connect discovery URL.
     * 
     * @return string|null Returns the value, or null if not set.
     */
    public function getOpenIdConnectUrl(): ?string {
        return $this->openIdConnectUrl;
    }

    /**
     * Returns the HTTP Authentication scheme.
     * 
     * @return string|null Returns the value, or null if not set.
     */
    public function getScheme(): ?string {
        return $this->scheme;
    }

    /**
     * Returns the type of the security scheme.
     * 
     * @return string
     */
    public function getType(): string {
        return $this->type;
    }

    /**
     * Sets a hint to identify how the bearer token is formatted.
     * 
     * @param string $bearerFormat The bearer token format (e.g., "JWT").
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setBearerFormat(string $bearerFormat): SecuritySchemeObj {
        $this->bearerFormat = $bearerFormat;

        return $this;
    }

    /**
     * Sets the description for security scheme.
     * 
     * @param string $description A description for security scheme.
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setDescription(string $description): SecuritySchemeObj {
        $this->description = $description;

        return $this;
    }

    /**
     * Sets configuration information for the OAuth2 flow types supported.
     * 
     * @param OAuthFlowsObj $flows OAuth Flows Object. REQUIRED for oauth2 type.
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setFlows(OAuthFlowsObj $flows): SecuritySchemeObj {
        $this->flows = $flows;

        return $this;
    }

    /**
     * Sets the location of the API key.
     * 
     * @param string $in Valid values are "query", "header", or "cookie". REQUIRED for apiKey type.
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setIn(string $in): SecuritySchemeObj {
        $this->in = $in;

        return $this;
    }

    /**
     * Sets the name of the header, query or cookie parameter to be used.
     * 
     * @param string $name The parameter name. REQUIRED for apiKey type.
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setName(string $name): SecuritySchemeObj {
        $this->name = $name;

        return $this;
    }

    /**
     * Sets the OpenID Connect discovery URL.
     * 
     * @param string $openIdConnectUrl Well-known URL to discover the provider metadata.
     * REQUIRED for openIdConnect type.
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setOpenIdConnectUrl(string $openIdConnectUrl): SecuritySchemeObj {
        $this->openIdConnectUrl = $openIdConnectUrl;

        return $this;
    }

    /**
     * Sets the name of the HTTP Authentication scheme.
     * 
     * @param string $scheme The HTTP Authentication scheme. REQUIRED for http type.
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setScheme(string $scheme): SecuritySchemeObj {
        $this->scheme = $scheme;

        return $this;
    }

    /**
     * Sets the type of the security scheme.
     * 
     * @param string $type Valid values are "apiKey", "http", "mutualTLS", "oauth2", "openIdConnect".
     * 
     * @return SecuritySchemeObj Returns self for method chaining.
     */
    public function setType(string $type): SecuritySchemeObj {
        $this->type = $type;

        return $this;
    }

    /**
     * Returns a Json object that represents the Security Scheme Object.
     * 
     * @return Json A Json object representation following OpenAPI 3.1.0 specification.
     */
    public function toJSON(): Json {
        $json = new Json([
            'type' => $this->getType()
        ]);

        if ($this->getDescription() !== null) {
            $json->add('description', $this->getDescription());
        }

        if ($this->getName() !== null) {
            $json->add('name', $this->getName());
        }

        if ($this->getIn() !== null) {
            $json->add('in', $this->getIn());
        }

        if ($this->getScheme() !== null) {
            $json->add('scheme', $this->getScheme());
        }

        if ($this->getBearerFormat() !== null) {
            $json->add('bearerFormat', $this->getBearerFormat());
        }

        if ($this->getFlows() !== null) {
            $json->add('flows', $this->getFlows());
        }

        if ($this->getOpenIdConnectUrl() !== null) {
            $json->add('openIdConnectUrl', $this->getOpenIdConnectUrl());
        }

        return $json;
    }
}
