name: Build PHP 8.5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    uses: WebFiori/workflows/.github/workflows/test-php.yaml@v1.2.5
    with:
      php-version: '8.5'
      phpunit-config: 'tests/phpunit.xml'

  code-coverage:
    name: Coverage
    needs: test
    uses: WebFiori/workflows/.github/workflows/coverage-codecov.yaml@v1.2.5
    with:
      php-version: '8.5'
      coverage-file: 'php-8.5-coverage.xml'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  code-quality:
    name: Code Quality
    needs: test
    uses: WebFiori/workflows/.github/workflows/quality-sonarcloud.yaml@v1.2.5
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release-prod:
    name: Prepare Production Release Branch / Publish Release
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [code-coverage, code-quality]
    uses: WebFiori/workflows/.github/workflows/release-php.yaml@v1.2.5
    with:
      branch: 'main'
