name: Build PHP 8.3

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 

    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [8.3]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring, sqlsrv
          tools: phpunit:9.5.20, composer
          
      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop
         
      - name: Install Dependencies
        run: composer install --prefer-source --no-interaction --no-dev
      
      - name: Execute Tests
        run: phpunit
        
      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  release_staging:
    needs:
      - "test"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          token: ${{ secrets.GITHUB_TOKEN }}
  release_prod:
    needs:
      - "test"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          token: ${{ secrets.GITHUB_TOKEN }}